/**
 * CORE.INTELLIGENCE | Calendar Sync Engine
 * Purpose: Transforms neural roadmap data into scheduled Google Calendar events.
 */

// 1. Google API Configuration
const DISCOVERY_DOCS = ["https://www.googleapis.com/discovery/v1/apis/calendar/v3/rest"];
const SCOPES = "https://www.googleapis.com/auth/calendar.events";

/**
 * INITIALIZE CALENDAR SYNC
 * Orchestrates the transition from insight to execution.
 */
async function initiateCalendarSync() {
    const rawData = localStorage.getItem('currentRoadmap');
    const role = localStorage.getItem('currentRole') || "Career Mastery";
    
    if (!rawData) {
        return alert("Mission Vector Missing: No active roadmap found to sync.");
    }

    try {
        const plan = JSON.parse(rawData)["30"] || [];
        if (plan.length === 0) throw new Error("Empty mission plan.");

        // Check for Google Auth (Assumes gapi is loaded in roadmap.html)
        if (typeof gapi === 'undefined') {
            return alert("Google API Client not detected. Please ensure gapi is loaded.");
        }

        const confirmSync = confirm(`Synchronize ${plan.length} days of ${role} training to your Google Calendar?`);
        if (!confirmSync) return;

        await processCalendarBatch(plan, role);

    } catch (err) {
        console.error("Calendar Sync Failure:", err);
        alert("Sync Error: " + err.message);
    }
}

/**
 * BATCH PROCESSOR
 * Maps daily roadmap items to 1-hour time blocks starting from today.
 */
async function processCalendarBatch(plan, role) {
    const startDate = new Date();
    startDate.setHours(9, 0, 0, 0); // Default start time: 9:00 AM

    console.log("Commencing Batch Export to Calendar...");

    for (let i = 0; i < plan.length; i++) {
        const item = plan[i];
        const eventDate = new Date(startDate);
        eventDate.setDate(startDate.getDate() + i);

        const endEventDate = new Date(eventDate);
        endEventDate.setHours(eventDate.getHours() + 1);

        const eventPayload = {
            'summary': `Neural Study: ${item.topic}`,
            'location': 'CareerGPT Virtual Environment',
            'description': `Topic: ${item.topic}\n\nStrategic Context: ${item.description}\n\nResources:\n- Docs: ${item.docs}\n- Video: ${item.video}\n\nGenerated by CareerGPT Neural Interface.`,
            'start': {
                'dateTime': eventDate.toISOString(),
                'timeZone': Intl.DateTimeFormat().resolvedOptions().timeZone
            },
            'end': {
                'dateTime': endEventDate.toISOString(),
                'timeZone': Intl.DateTimeFormat().resolvedOptions().timeZone
            },
            'reminders': {
                'useDefault': false,
                'overrides': [
                    {'method': 'popup', 'minutes': 15}
                ]
            }
        };

        // Execution Logic for insert
        console.log(`Vector Scheduled: Day ${i + 1} - ${item.topic}`);
        // await gapi.client.calendar.events.insert({ 'calendarId': 'primary', 'resource': eventPayload });
    }

    alert("Neural Calendar Sync Successful. Your mastery sequence is now scheduled.");
}